version: "3.8"

services:
  mqtt-bridge:
    build: .
    container_name: mqtt-wss-bridge
    restart: unless-stopped
    environment:
      LOCAL_BROKER: mosquitto   # or mosquitto container name
      LOCAL_PORT: 1883
      REMOTE_BROKER: ws.rabbitmq.razorback.tk
      REMOTE_PORT: 443
      REMOTE_USER: admin
      REMOTE_PASS: admin
      REMOTE_PATH: /ws
      TOPIC: "#"
